library(dplyr)
epc <- read.table("household_power_consumption.txt", header = TRUE, sep = ";", stringsAsFactors = FALSE)
epc$dt <- as.POSIXct(paste(epc$Date, epc$Time), format = "%d/%m/%Y %H:%M:%S")
epc2 <- tbl_df(epc)
rm(epc)
epc <- filter(epc2, dt >= "2007-02-01 00:00:00", dt <= "2007-02-02 23:59:59")
rm(epc2)
epc$Global_active_power <- as.numeric(epc$Global_active_power)
png(file = "plot2.png", width = 480, height = 480, units = "px")
with(epc, plot(dt, Global_active_power, type = "l", xlab="", ylab="Global Active Power (kilowatts)"))
dev.off()
